In [ ]:
import tensorflow as tf

print(tf.__version__)

2.4.1


In [ ]:
# Create tensors with tf.constant()

scalar = tf.constant(7)

scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Checking the number of dimensions of a tensor (ndim)

scalar.ndim

0

In [ ]:
# Create a vector

vector = tf.constant([10,10])

vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# Create a matrix

matrix = tf.constant([[10,7],
                     [7,10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix 

another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                             [8.,9.]] , dtype = tf.float16)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Create a tensor

tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                      [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
# creating tensors using tf.Variable

changeable_tensor = tf.Variable([10 , 7])

unchangeable_tensor = tf.constant([10,7])

changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# chaging values of a variable using .assign()

changeable_tensor[0].assign(7)

changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
 # Creating random tensors

 random_1 = tf.random.Generator.from_seed(7)
 random_1 = random_1.normal(shape = (3,2))

 random_2 = tf.random.Generator.from_seed(7)
 random_2 = random_2.normal(shape = (3,2))

 random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
# They are the same because we gave them a seed.

# We set seed for reproducibility

In [ ]:
# Shuffle a tensor 

unshuffled_tensor = tf.constant([[10,7],
                                  [3,4],
                                  [2,5]])

tf.random.shuffle(unshuffled_tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
# We can also give a seed to get the same result each time. 

In [ ]:
# Others ways to make tensors

In [ ]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape = (3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# Conveting numpy arrays into tensors

In [ ]:
import numpy as np

numpy_A = np.arange(1,25,dtype = np.int32)

numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
A.shape

TensorShape([24])

In [ ]:
B = tf.constant(numpy_A , shape = (2,3,4))

B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information from tensors

* shape
* rank
* axis
* size

In [ ]:
# create a rank 4 tensor (4 dimensions)

rank4tensor = tf.zeros(shape = [2,3,4,5])

rank4tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank4tensor.ndim

4

In [ ]:
rank4tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
tf.size(rank4tensor) # 2*3*4*5

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [ ]:
tf.size(rank4tensor).numpy()

120

In [ ]:
rank4tensor.dtype

tf.float32

### Manipulating tensors (tensor operation)

In [ ]:
tensor = tf.constant([[10,7],[3,4]])

tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

### Matrix multiplication

In [ ]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# matmul can also be written as @

In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tf.tensordot(tensor,tensor,1) # third argument is axes

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

### Changing dtype 

In [ ]:
# Changing dtype from float32 to float16 (reduced precision)

A = tf.constant([1.7,7.4])

print(A,A.dtype)
print()

B = tf.constant([7,10])

print(B,B.dtype)
print()



tf.Tensor([1.7 7.4], shape=(2,), dtype=float32) <dtype: 'float32'>

tf.Tensor([ 7 10], shape=(2,), dtype=int32) <dtype: 'int32'>



In [ ]:
C = tf.cast(A,dtype = tf.float16)

C,C.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# int32 to float32

D = tf.cast(B,dtype=tf.float32)

D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

### Aggregation

Forms of aggregation:-

* Get the maximum
* Get the minimum
* Get the mean
* Get the sum

In [ ]:
# create a random tensor with values between 0 and 100 size 50

random_tensor = tf.constant(np.random.randint(0,100,size = 50))

random_tensor


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([86, 29, 87, 55, 80, 77, 66, 45, 17, 69, 86, 89, 15, 30, 18, 15,  1,
       66, 32, 12, 47, 72, 76, 97,  3, 10, 64, 71,  0, 44, 10, 42, 19, 33,
       18, 43, 48, 44, 63, 99, 81, 22, 28,  8, 15, 18, 35, 64, 73, 80])>

In [ ]:
tf.size(random_tensor),random_tensor.shape,random_tensor.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

##### minimum

In [ ]:
tf.reduce_min(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

##### maximum

In [ ]:
tf.reduce_max(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

##### mean

In [ ]:
tf.reduce_mean(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

##### sum

In [ ]:
tf.reduce_sum(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2302>

### Finding variance and standard deviation using Tensorflow 

#### Variance

##### method-1

In [ ]:
import tensorflow_probability as tfp

In [ ]:
tfp.stats.variance(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=837>

##### method-2 

In [ ]:
# A float tensor is needed so we will typecast also since random_tensor is int32

tf.math.reduce_variance(tf.cast(random_tensor,dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=837.4384>

#### Standard deviation

In [ ]:
# A float tensor is needed so we will typecast also since random_tensor is int32

tf.math.reduce_std(tf.cast(random_tensor,dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.938528>

### Finding Positional maximum and minimum

In [ ]:
# creating a new tensor

new_tensor = tf.random.uniform(shape = [50])

new_tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.5835383 , 0.55176437, 0.4176426 , 0.9821495 , 0.775728  ,
       0.44207132, 0.35310626, 0.99085295, 0.29326522, 0.6163713 ,
       0.82536674, 0.59617865, 0.02399445, 0.19448233, 0.37722576,
       0.49609303, 0.59906924, 0.6176189 , 0.26681805, 0.74351406,
       0.9776645 , 0.70404303, 0.30544126, 0.9757434 , 0.15806234,
       0.5807102 , 0.46054995, 0.6167288 , 0.23638535, 0.03772986,
       0.2982129 , 0.7213969 , 0.19252384, 0.62800705, 0.54891336,
       0.9970138 , 0.7548369 , 0.94771814, 0.749441  , 0.93501437,
       0.9161136 , 0.47439134, 0.8369049 , 0.6080326 , 0.41166604,
       0.692559  , 0.9056765 , 0.14361763, 0.13442111, 0.89765704],
      dtype=float32)>

In [ ]:
# Finding index of the positional maximum

tf.argmax(new_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=35>

In [ ]:
# Finding the largest value

new_tensor[tf.argmax(new_tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9970138>

In [ ]:
# Finding index of the positional minimum

tf.argmin(new_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=12>

In [ ]:
# Finding the smallest value

new_tensor[tf.argmin(new_tensor)]


<tf.Tensor: shape=(), dtype=float32, numpy=0.023994446>

In [ ]:
# another way to find max min was

tf.reduce_max(new_tensor) , tf.reduce_min(new_tensor)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9970138>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.023994446>)

 ### Squeezing a tensor

In [ ]:
# removes all single dimensions from a tensor

tens = tf.constant(tf.random.uniform(shape = [50]),shape = (1,1,1,1,1,50))

tens

<tf.Tensor: shape=(1, 1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[[0.1584996 , 0.7753482 , 0.7683886 , 0.35933006,
            0.7700856 , 0.3008685 , 0.68974555, 0.08698082,
            0.6681739 , 0.7109015 , 0.81943035, 0.62822616,
            0.6313598 , 0.7062546 , 0.12523031, 0.90516007,
            0.48364782, 0.55391896, 0.7759702 , 0.21220183,
            0.01102984, 0.746369  , 0.9161763 , 0.78753304,
            0.02523959, 0.7433517 , 0.78905845, 0.23813307,
            0.73369074, 0.90305126, 0.9318918 , 0.3583821 ,
            0.71525025, 0.565683  , 0.08866119, 0.6093185 ,
            0.9589113 , 0.94732666, 0.09079623, 0.3235711 ,
            0.8470495 , 0.5100683 , 0.92556643, 0.33407426,
            0.06157529, 0.07791877, 0.908954  , 0.5051923 ,
            0.8160615 , 0.5181309 ]]]]]], dtype=float32)>

In [ ]:
squeezed_tens = tf.squeeze(new_tensor)

squeezed_tens , squeezed_tens.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.5835383 , 0.55176437, 0.4176426 , 0.9821495 , 0.775728  ,
        0.44207132, 0.35310626, 0.99085295, 0.29326522, 0.6163713 ,
        0.82536674, 0.59617865, 0.02399445, 0.19448233, 0.37722576,
        0.49609303, 0.59906924, 0.6176189 , 0.26681805, 0.74351406,
        0.9776645 , 0.70404303, 0.30544126, 0.9757434 , 0.15806234,
        0.5807102 , 0.46054995, 0.6167288 , 0.23638535, 0.03772986,
        0.2982129 , 0.7213969 , 0.19252384, 0.62800705, 0.54891336,
        0.9970138 , 0.7548369 , 0.94771814, 0.749441  , 0.93501437,
        0.9161136 , 0.47439134, 0.8369049 , 0.6080326 , 0.41166604,
        0.692559  , 0.9056765 , 0.14361763, 0.13442111, 0.89765704],
       dtype=float32)>, TensorShape([50]))

# ONE HOT ENCODING

In [ ]:
some_list = [0,1,2,3]

tf.one_hot(some_list , depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# specify custom values for one hot encoding

tf.one_hot(some_list , depth = 4, on_value = "Aryan",off_value = "Anku")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Aryan', b'Anku', b'Anku', b'Anku'],
       [b'Anku', b'Aryan', b'Anku', b'Anku'],
       [b'Anku', b'Anku', b'Aryan', b'Anku'],
       [b'Anku', b'Anku', b'Anku', b'Aryan']], dtype=object)>

# Some more math operations on tensors

In [ ]:
# creating a tensor

ten = tf.range(1,10)

ten

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# square

tf.square(ten)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# sqr root

tf.sqrt(tf.cast(ten,dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# log

tf.math.log(tf.cast(ten,dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>